In [29]:
import numpy as np
import pandas as pd
import pickle
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load Dataset

In [30]:
df=pd.read_csv("7 churn.csv")

In [31]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [32]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [33]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

# keep important columns which ic called feature engineering

In [34]:
# Feature Engineering
col_to_keep = ['gender', 'SeniorCitizen', 'Partner', 'Dependents',
               'tenure', 'PhoneService', 'MultipleLines', 'Contract', 'TotalCharges', 'Churn']

In [35]:
df=df[col_to_keep]

In [36]:
df.iloc[0]

gender                     Female
SeniorCitizen                   0
Partner                       Yes
Dependents                     No
tenure                          1
PhoneService                   No
MultipleLines    No phone service
Contract           Month-to-month
TotalCharges                29.85
Churn                          No
Name: 0, dtype: object

In [37]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,Contract,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,Month-to-month,29.85,No
1,Male,0,No,No,34,Yes,No,One year,1889.5,No
2,Male,0,No,No,2,Yes,No,Month-to-month,108.15,Yes
3,Male,0,No,No,45,No,No phone service,One year,1840.75,No
4,Female,0,No,No,2,Yes,No,Month-to-month,151.65,Yes

In [38]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'Contract', 'TotalCharges', 'Churn'],
      dtype='object')

# Lets encode binary columns using LableEncoder

In [39]:
le = LabelEncoder()
bin_col = ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'Contract', 'Churn']
for col in bin_col:
    df[col] = le.fit_transform(df[col])

In [9]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,Contract,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,29.85,0
1,1,0,0,0,34,1,0,1,1889.5,0
2,1,0,0,0,2,1,0,0,108.15,1
3,1,0,0,0,45,0,1,1,1840.75,0
4,0,0,0,0,2,1,0,0,151.65,1

# train_test_split

In [40]:
# Train/Test Split
X = df.drop('Churn', axis=1)
y = df['Churn']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [41]:
# Handle TotalCharges
X_train["TotalCharges"] = pd.to_numeric(X_train["TotalCharges"], errors='coerce')
X_test["TotalCharges"] = pd.to_numeric(X_test["TotalCharges"], errors='coerce')
X_train["TotalCharges"].fillna(X_train["TotalCharges"].mean(), inplace=True)
X_test["TotalCharges"].fillna(X_train["TotalCharges"].mean(), inplace=True)  # ✅ use train mean

C:\Users\A I TECH\AppData\Local\Temp\ipykernel_17940\2924180823.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train["TotalCharges"].fillna(X_train["TotalCharges"].mean(), inplace=True)
C:\Users\A I TECH\AppData\Local\Temp\ipykernel_17940\2924180823.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test["TotalCharges"].fillna(X_train["TotalCharges"].mean(), inplace=True)  # ✅ use train mean

In [13]:
# StandardScaler
ss = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [16]:
# Train Model
lg = LogisticRegression()
lg.fit(X_train, y_train)

LogisticRegression()

In [17]:
y_pred = lg.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7757274662881476

# Save Model

In [18]:

pickle.dump(lg, open("Linear_Churn_model.pkl", "wb"))
pickle.dump(ss, open("scaler.pkl", "wb"))

# Classification model

In [45]:
# Prediction Function
def predictive(gender, seniorCitizen, partner, dependents, tenure,
               phoneService, multipleLines, contract, totalCharges):
    
    gender = 1 if gender == "Male" else 0
    partner = 1 if partner == "Yes" else 0
    dependents = 1 if dependents == "Yes" else 0
    phoneService = 1 if phoneService == "Yes" else 0
    multipleLines = 1 if multipleLines == "Yes" else 0  
    contract = {"Month-to-month": 0, "One year": 1, "Two year": 2}.get(contract, 0)

In [46]:
# Define input values first
gender = "Female"
seniorCitizen = 0
partner = "Yes"
dependents = "No"
tenure = 1
phoneService = "No"
multipleLines = "No phone service"
contract = "Month-to-month"
totalCharges = 29.85

In [47]:
result = predictive(gender, seniorCitizen, partner, dependents, tenure,
                    phoneService, multipleLines, contract, totalCharges)
print("Not Churn" if result == 0 else "Churn")

Churn